# Part of `travis-lazarus` (https://github.com/nielsAD/travis-lazarus)
# License: MIT

language: generic
sudo: required
dist: trusty

os:
  - linux

env:
  global:
    - WINEPREFIX=~/.winelaz
    - DISPLAY=:99.0
  matrix:
      # - LAZ_PKG=true  # Use the latest version from the default package manager
      #   - LAZ_VER=1.4.4 # Use specific (binary) release
    - LAZ_VER=1.6.2

matrix:
  include:
      #    - os: linux
      #      env: LAZ_VER=1.4.4  LAZ_ENV=wine WINEARCH=win32 LAZ_OPT="--os=win32 --cpu=i386"
      #    - os: linux
      #      env: LAZ_VER=1.6.2  LAZ_ENV=wine WINEARCH=win32 LAZ_OPT="--os=win32 --cpu=i386"
      #    - os: linux
      #      env: LAZ_VER=1.4.4  LAZ_ENV=wine WINEARCH=win64 LAZ_OPT="--os=win64 --cpu=x86_64"
    - os: linux
      env: LAZ_VER=1.6.2  LAZ_ENV=wine WINEARCH=win64 LAZ_OPT="--os=win64 --cpu=x86_64"
      #    - os: linux
      #      env: LAZ_VER=1.4.4  LAZ_ENV=qemu-arm LAZ_OPT="--os=linux --cpu=arm"
      #    - os: linux
      #      env: LAZ_VER=1.6.2  LAZ_ENV=qemu-arm LAZ_OPT="--os=linux --cpu=arm"

before_install:
  # Start virtual display server
  - Xvfb $DISPLAY &
  - chmod +x ./tests/travis.install.py

install:
  # Install prerequisites (fpc/lazarus/wine/qemu)
  - ./tests/travis.install.py
  - /bin/bash -c "sudo apt-get install qemu-system-x86"

script:
  - lazbuild $LAZ_OPT ./tests/ToroHello.lpi               # Build ToroHello.lpi project
  - /bin/bash -c "ls -al ./tests/"
  - bash "./tests/TestHello.sh"                            # Run test of ToroHello

notifications:
  email:
    on_success: false
    on_failure: change
